### ISSUE TITLE
Launch todo

### ISSUE THREAD

**Issue by jamilbk** [firezone/probe#4]
```[tasklist]
- [ ] https://github.com/firezone/probe/issues/5
- [ ] https://github.com/firezone/probe/issues/6
- [ ] https://github.com/firezone/probe/issues/9
- [ ] https://github.com/firezone/probe/issues/11
- [ ] https://github.com/firezone/probe/issues/16
- [ ] https://github.com/firezone/probe/issues/12
- [ ] https://github.com/firezone/probe/issues/7
- [ ] https://github.com/firezone/probe/issues/8
- [ ] https://github.com/firezone/probe/issues/10
- [ ] https://github.com/firezone/probe/issues/13
- [ ] https://github.com/firezone/probe/issues/15
- [ ] https://github.com/firezone/probe/issues/17
- [ ] https://github.com/firezone/probe/issues/14
```

**Comment by jamilbk** [comment]
@AndrewDryga I believe we're ready to publish this. The token expiration actually happened on each subsequent run because of a copy-to-clipboard bug with the `textarea`. That's been fixed, and the token lifetime increased to 5 minutes.

I also increased the machine size and scaled more app instances because the map SVG is fairly large (10,000 LOC).

Fixing tests and using cookie-based session can be further refinements that I don't think are blocking public consumption currently.
